### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by subcritical71** [paulw11/homebridge-elkm1#27]
I'm sure this is a nuisance warning at the moment, but I'm starting to get this working on every restart of homebridge;

```
(node:62285) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 CS listeners added to [Elk]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at Elk.addListener (events.js:467:10)
    at Elk.once (events.js:498:8)
    at /usr/local/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:178:18
    at new Promise (<anonymous>)
    at Elk.requestOutputStatusReport (/usr/local/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:176:16)
    at ElkOutput.getOutput (/usr/local/lib/node_modules/homebridge-elkm1/src/accessories/ElkOutput.ts:56:25)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1450:32)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
```

**Comment by paulw11** [comment]
This is a warning and I think I can fix it by calling `setMaxListeners(0)`, but I want to make sure it isn't actually a problem first.  How many contacts/zones do you have in your home bridge config for the elkm1?

**Comment by subcritical71** [comment]
Zones 10, contacts/outputs 13 (one is for garage door)

**Comment by subcritical71** [comment]
Just another data point, I am getting some unstableness in HomeKit with the hb-elkm1 accessories. It seems to become unresponsive about twice per day. I cannot control the zones/outputs or get their correct status. The messages in the first post above are still occurring throughout the day but at the moment I don't know if its related. I normally end up rebooting the Mac I have HB installed on as cycling the hb-elkm1 plugin in HB doesn't solve the issue. I have hb-smart-irrigation also installed/running and this continues to function correctly. This could be a HB issue or hb-elkm1. I've put hb-elkm1 in a child bridge to see if things improve.

**Comment by hjdhjd** [comment]
@paulw11 The max listeners warning is just that...we've had it come up in other parts of homebridge such as camera plugins. Generally speaking, here's an example of how you can deal with it:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/7fdd811e6c8393c8315480296a1486a7c7d374ca/src/protect-stream.ts#L43

Total non-sequitur:

I'm going to setup your Elk plugin for the first time in the next week or so...I've got more than 60 zones to deal with and 2 partitions. Out of curiosity: have you tested this plugin with that many zones? I'm curious what I'm in store for. :smile: Bonus question: does your plugin support partitions (where I can arm and disarm certain collections of zones independently of each other)? I presume it would manifest itself with basically two SecuritySystem accessories...

**Comment by paulw11** [comment]
Thanks for the comment. 

You will need to create two instances of homebridge-elkm1 in your config. Each will specify a different area and set of zones but have the same IP address.  

Area support was added in the recent re-write so be sure to let me know if you have any problems.

**Comment by hjdhjd** [comment]
No worries. I'll take a look. Appreciate the context around the limitation in areas. I might take a pass at looking through the codebase and seeing about adding support for multiple areas / partitions in a single instance once I play around with things a bit more and better understand how the Elk communicates with the world.

Thanks for your community contribution, and hope I can add to it as well as you progress.
