### ISSUE TITLE
Getting kicked out of Homebridge with event error

### ISSUE THREAD

**Issue by RAGR1** [paulw11/homebridge-elkm1#4]
Hey Paul, Every couple of days I get kicked out of Homebridge with this error. I run Homebridge in Terminal again and it'll be fine for another day or two but I can't figure out what this error is but it looks related to elk module. Any ideas?

events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (ECONNRESET)
    at Elk.emit (events.js:163:17)
    at Socket.connection.on (/usr/local/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:45:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by paulw11** [comment]
Thanks for opening the issue.  I have updated the code to address this, however this does indicate that all isn't well with your M1XEP; perhaps it has power supply issues as this error occurs when the XEP reboots
