### ISSUE TITLE
homebridge won't run anymore. Looks like "Unexpected Token"

### ISSUE THREAD

**Issue by RAGR1** [paulw11/homebridge-elkm1#7]
Sorry I'm not versed enough to figure this out on my own but I'm trying to learn. I updated Node.js and my accessories stopped working. I tried to fix it and homebridge stopped loading. I deleted everything I could find and started over with the results below. It looks like a hang up with the ElkM1 plugin but I'm not sure.

$ homebridge
[2/6/2018, 3:48:55 PM] Loaded plugin: homebridge-elkm1
/usr/local/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:11
    constructor(port = 2101, host = '192.168.1.0', options = {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-elkm1/index.js:21:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:160:14)
    at Array.forEach (native)

**Comment by paulw11** [comment]
That is showing an error in the elkmon package that homebridge-elkm1 uses.  That package hasn't been updated since July last year.  

What version of Node.js did you upgrade to?  Perhaps try uninstalling and re-installing homebridge-elkm1 using `npm`?

**Comment by RAGR1** [comment]
Node v4.8.7. I tried uninstalling and re-installing but still hanging up. Maybe when this is all fixed, I will be grateful that I learned something but right now it's irritating.

$ homebridge
[2/7/2018, 12:21:16 PM] Loaded plugin: homebridge-elkm1
/usr/local/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:11
    constructor(port = 2101, host = '192.168.1.0', options = {
                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-elkm1/index.js:21:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:160:14)
    at Array.forEach (native)

**Comment by RAGR1** [comment]
Uninstalled Homebridge, Node.js, and all accessories. Installed the newest version of Node.js, homebridge, and all accessories. Everything working great. The hangup is gone. Thanks for looking at it for me.
